apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin-panel.fullname" . }}-config
data:
  config.json: |
    {
      "BAS_API_URL": "{{ .Values.adminpanel.configmap.basURL }}",
      "TRACES_API_URL": "{{ .Values.adminpanel.configmap.traceURL }}",
      "BENCH_API_URL": "{{ .Values.adminpanel.configmap.benchURL }}" 
    }