apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-panel.fullname" . }}
  namespace: "{{ .Values.adminpanel.ns }}"
  labels:
    app: {{ include "admin-panel.fullname" . }}
spec:
  ports:
    - port: {{ .Values.adminpanel.service.port }}
      targetPort: {{ .Values.adminpanel.service.port }}
      protocol: TCP
  selector:
    app: {{ include "admin-panel.fullname" . }}
  type: ClusterIP