import type { IMockTraceDemo } from "./types";

/** Демо-трейс для прототипа без живого API (UIR-4.8 – UIR-4.17). */
export const TRACE_DEMO_MOCK: IMockTraceDemo = {
  traceId: "demo",
  user_query: "Найди на Ozon беспроводные наушники до 5000 рублей",
  session_id: "sess-demo-8f3a2b1c",
  chat_id: "chat-demo-44e91d0a",
  user_agent: "Mozilla/5.0 (demo prototype)",
  created_at: "2026-06-23T10:00:00.000Z",
  cycles: [
    {
      id: "cycle-planner-1",
      agent_name: "planner",
      model_name: "GigaHF-GV-38B-29.4-UI-latest",
      total_tokens: 1842,
      duration_s: 3.1,
      status: "success",
    },
    {
      id: "cycle-navigator-1",
      agent_name: "navigator",
      model_name: "GigaHF-Qwen3.5-27B",
      total_tokens: 3201,
      duration_s: 4.8,
      status: "success",
    },
    {
      id: "cycle-navigator-2",
      agent_name: "navigator",
      model_name: "GigaHF-Qwen3.5-27B",
      total_tokens: 2905,
      duration_s: 2.4,
      status: "fail",
    },
  ],
  timeline: {
    traceId: "demo",
    originAt: "2026-06-23T10:00:00.000Z",
    totalDurationS: 24.5,
    segments: [
      {
        id: "seg-m1",
        type: "model",
        cycleId: "cycle-planner-1",
        label: "planner",
        agentName: "planner",
        modelName: "GigaHF-GV-38B-29.4-UI-latest",
        startOffsetS: 0,
        durationS: 3.1,
        status: "success",
      },
      {
        id: "seg-p1",
        type: "plugin",
        cycleId: "cycle-planner-1",
        label: "go_to_url",
        actionName: "go_to_url",
        actionIndex: 0,
        startOffsetS: 4.0,
        durationS: 1.2,
        status: "success",
      },
      {
        id: "seg-m2",
        type: "model",
        cycleId: "cycle-navigator-1",
        label: "navigator",
        agentName: "navigator",
        modelName: "GigaHF-Qwen3.5-27B",
        startOffsetS: 6.0,
        durationS: 4.8,
        status: "success",
      },
      {
        id: "seg-p2",
        type: "plugin",
        cycleId: "cycle-navigator-1",
        label: "click_element",
        actionName: "click_element_by_index",
        actionIndex: 0,
        startOffsetS: 11.5,
        durationS: 2.1,
        status: "success",
      },
      {
        id: "seg-p3",
        type: "plugin",
        cycleId: "cycle-navigator-1",
        label: "input_text",
        actionName: "input_text",
        actionIndex: 1,
        startOffsetS: 14.0,
        durationS: 1.8,
        status: "success",
      },
      {
        id: "seg-m3",
        type: "model",
        cycleId: "cycle-navigator-2",
        label: "navigator",
        agentName: "navigator",
        modelName: "GigaHF-Qwen3.5-27B",
        startOffsetS: 17.0,
        durationS: 2.4,
        status: "fail",
      },
      {
        id: "seg-p4",
        type: "plugin",
        cycleId: "cycle-navigator-2",
        label: "scroll",
        actionName: "scroll",
        actionIndex: 0,
        startOffsetS: 20.5,
        durationS: 0.05,
        status: "failed",
      },
    ],
  },
};
