image:
  repository: registry.sberdevices.ru/gigaoper/browser-agent-service-admin-panel
  tag: main-latest

adminpanel:
  enabled: true
  name: "adminpanel"
  replicas: 3
  ns: "p-gigaoper-utils"
  service:
    port: 8080
  configmap:
    name: "adminpanel-config"
    basURL: "https://serviceapi-prod-gigaoper.apps.advosp.sberdevices.ru"
    traceURL: "https://trace-prod-gigaoper.apps.advosp.sberdevices.ru"
    benchURL: "https://orchestrator-prod-gigaoper.apps.advdagod.sberdevices.ru"
  imagePullSecrets:
    name: "gigaoper-dropapp-adminpanel"
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
clusterDomain: "apps.advosp.sberdevices.ru"
groupName: "gigaoper"
route:
  host: ""
  old:
    enabled: false
